import { storage } from "./storage";
import { namedEntities } from "./name-alias";

/**
 * Which room types this turn is actually ABOUT — the ones that earn a card.
 *
 * The signal is the guest's question plus the reply we just wrote, NOT the
 * retrieved passages.
 *
 * This function used to read `passages`, and did so with a Damerau-Levenshtein
 * distance of ≤1 over every token of ≥4 characters, "tolerant of typos &
 * paraphrasing". Measured against the running kiosk, that produced 6-10 room
 * cards on EVERY turn, including the entire 10-type catalogue for "Wifi có
 * miễn phí không?" and for a broken-air-con complaint. Two compounding
 * reasons:
 *
 *  - Room names fold to ordinary Vietnamese words — "phong", "giuong",
 *    "huong", "bien", "biet", "thu". A pool passage says "hướng biển", so
 *    every ocean-view room matched it; distance ≤1 also makes "khong" (the
 *    everyday word for "no") match "phong", so nearly any passage matched
 *    the villas. Fuzziness over generic tokens is not typo tolerance, it is
 *    a wildcard.
 *  - Retrieval returns five passages whether or not they are relevant. Asked
 *    the breakfast hours, the top passage was "Phòng Gym / Fitness". Cards
 *    built from that are cards built from retrieval noise, and the guest
 *    sees a wall of offers they did not ask for.
 *
 * Matching the reply instead of the guest's raw typing is also what makes the
 * fuzzy pass unnecessary: the reply is generated by us and spells the room
 * name correctly, so a guest who types "deluxue giuong doi" still gets the
 * right card as long as the answer names the room — and a guest who never
 * mentioned a room gets none.
 *
 * `namedEntities` carries the matching rules and why each is needed: whole
 * adjacent tokens in a shared vocabulary, most-specific name wins. `code` and
 * `nameVi` are passed as two aliases for the same room because a guest names
 * it in one language or the other.
 *
 * `passages` is still accepted so the call signature and the trace entry are
 * unchanged, but it is deliberately not consulted.
 */
export function detectReferencedRoomTypes(
  _passages: { title: string; category: string; content?: string; body?: string }[],
  focusText = "",
): { code: string; name: string }[] {
  if (!focusText.trim()) return [];
  return namedEntities(
    focusText,
    storage.listRoomTypes().map((r) => ({
      name: r.nameVi,
      alt: r.code,
      item: { code: r.code, name: r.nameVi },
    })),
  );
}
