/**
 * Build a demo dataset that the dashboards can measure honestly.
 *
 * The problem this replaces: `seed.ts` wrote ninety-five conversations with no
 * messages, a `rand()` sentiment and a `rand()` topic. Every Insights panel
 * then reported on fixtures — "What guests ask about" was 6/101 real, "Team
 * load" was 0/115 real, and the sentiment pie was dice. A demo built on that
 * shows a customer a picture of nothing.
 *
 * THE RULE HERE: this script does not write conversation content. It drives the
 * real HTTP API, so every reply is generated by the real agent, every sentiment
 * label comes from the real classifier, every task is raised by the real
 * escalation paths, and every latency is a measured one. What the dashboards
 * then show is the product's own behaviour.
 *
 * THE ONE EXCEPTION, stated plainly: timestamps are moved afterwards to spread
 * the conversations across fourteen days, because a chart of "the last 14 days"
 * is useless when everything happened in one afternoon. The words, the labels,
 * the tasks and the durations are all genuine; only when they happened is
 * arranged. Nothing else is invented.
 *
 * Requires the dev server on :5000 and Ollama up. Takes 10-20 minutes — every
 * turn is a real model call on one GPU.
 *
 *   npx tsx scripts/build-demo-data.ts            # dry run: show the plan
 *   npx tsx scripts/build-demo-data.ts --apply
 *   npx tsx scripts/build-demo-data.ts --purge    # remove demo data only
 */
import "dotenv/config";
import Database from "better-sqlite3";

const BASE = process.env.DEMO_BASE || "http://localhost:5000";
const TOKEN = process.env.STAFF_API_TOKEN || "";
const APPLY = process.argv.includes("--apply");
const PURGE = process.argv.includes("--purge");

/* Marks every row this script owns, so a re-run can clear its own work without
   touching the eight original demo guests or anything a human typed. */
const TAG = "[demo-cohort]";

const db = new Database(process.env.DB_FILE || "data.db");
db.pragma("busy_timeout = 8000");

const api = async (path: string, init?: RequestInit) => {
  const r = await fetch(`${BASE}${path}`, {
    ...init,
    headers: { "Content-Type": "application/json", "x-staff-token": TOKEN, ...(init?.headers ?? {}) },
  });
  if (!r.ok) throw new Error(`${init?.method ?? "GET"} ${path} -> ${r.status} ${await r.text()}`);
  return r.json();
};

/* ---------------------------------------------------------------- cohort */

type Turn = { text: string; staffReply?: string };
type Persona = {
  name: string; phone: string; email: string; lang: string; vip: string;
  prefs: string[]; notes: string; stays: number;
  /** Which day of the last 14 this stay's conversation is dated to. */
  dayAgo: number;
  turns: Turn[];
};

/* Fifteen guests, six languages, and a spread of intents chosen to exercise
   every path the dashboards report on: plain lookups, an upsell question, a
   booking change that must escalate, calm fault reports that must NOT read as
   complaints, and complaints in several shapes — direct, implied, sarcastic,
   mixed, and unaccented Vietnamese (the classifier's known weak spot, included
   on purpose so the demo shows the real behaviour rather than a curated one). */
const COHORT: Persona[] = [
  {
    name: "Đặng Thu Trang", phone: "+84903118742", email: "trang.dang@example.vn", lang: "vi",
    vip: "gold", prefs: ["Tầng cao", "Phòng yên tĩnh"], notes: "Đi công tác, đặt trực tiếp.", stays: 3, dayAgo: 13,
    turns: [
      { text: "Giá phòng Deluxe giường đôi là bao nhiêu ạ?" },
      { text: "Gói nào có bao gồm bữa sáng không?" },
    ],
  },
  {
    name: "Bùi Quốc Hưng", phone: "+84907442310", email: "hung.bui@example.vn", lang: "vi",
    vip: "none", prefs: ["Gần hồ bơi"], notes: "Gia đình có trẻ nhỏ.", stays: 1, dayAgo: 12,
    turns: [
      { text: "Hồ bơi mở cửa mấy giờ và có khu riêng cho trẻ em không?" },
      { text: "Phòng tôi ồn kinh khủng, cả đêm không ngủ được, quá thất vọng" },
    ],
  },
  {
    name: "James Whitfield", phone: "+447700900431", email: "j.whitfield@example.co.uk", lang: "en",
    vip: "silver", prefs: ["Late breakfast"], notes: "Booked via agent.", stays: 2, dayAgo: 12,
    turns: [
      { text: "What time does the main restaurant serve dinner?" },
      { text: "Can I book a table for four at seven tonight?", staffReply: "Dạ em đã giữ bàn 4 người lúc 19:00 tại Nhà hàng Bách Giai cho anh ạ." },
    ],
  },
  {
    name: "Park Min-jun", phone: "+821087334512", email: "minjun.park@example.kr", lang: "ko",
    vip: "gold", prefs: ["Spa"], notes: "스파 예약 선호.", stays: 5, dayAgo: 11,
    turns: [
      { text: "아코야 스파 트리트먼트 종류와 운영시간을 알려주세요" },
      { text: "회원 등급에 따라 스파 할인이 얼마나 되나요?" },
    ],
  },
  {
    name: "Sato Haruka", phone: "+818045512203", email: "haruka.sato@example.jp", lang: "ja",
    vip: "none", prefs: ["Quiet floor"], notes: "初回滞在。", stays: 1, dayAgo: 10,
    turns: [
      { text: "205号室のエアコンが効かないので確認をお願いします" },
      { text: "ケーブルカーの運行時間を教えてください" },
    ],
  },
  {
    name: "Chen Yuxin", phone: "+8613800138221", email: "yuxin.chen@example.cn", lang: "zh",
    vip: "platinum", prefs: ["海景房"], notes: "常客，偏好高层海景。", stays: 9, dayAgo: 9,
    turns: [
      { text: "请问 VinWonders 的门票怎么买，酒店有优惠吗？" },
      { text: "前台态度很差，我要投诉" },
    ],
  },
  {
    name: "Olga Petrova", phone: "+79161234872", email: "o.petrova@example.ru", lang: "ru",
    vip: "silver", prefs: ["Поздний выезд"], notes: "Путешествует с семьёй.", stays: 2, dayAgo: 8,
    turns: [
      { text: "Мне нужен поздний выезд до 16:00, это возможно?" },
      { text: "Уже третий раз прошу убрать номер" },
    ],
  },
  {
    name: "Lý Thanh Vân", phone: "+84918227634", email: "van.ly@example.vn", lang: "vi",
    vip: "none", prefs: [], notes: "Đặt qua OTA.", stays: 1, dayAgo: 7,
    turns: [
      { text: "gia phong nay qua dat so voi chat luong, phong con khong co du khan tam" },
    ],
  },
  {
    name: "Marco Rossi", phone: "+393401122780", email: "m.rossi@example.it", lang: "en",
    vip: "none", prefs: ["Sea view"], notes: "Honeymoon.", stays: 1, dayAgo: 7,
    turns: [
      { text: "Is high-speed wifi included in the room rate?" },
      { text: "Are pets allowed at the resort?" },
    ],
  },
  {
    name: "Nguyễn Hải Đăng", phone: "+84934556218", email: "dang.nguyen@example.vn", lang: "vi",
    vip: "diamond", prefs: ["Biệt thự", "Đưa đón sân bay"], notes: "Khách VIP dài hạn.", stays: 21, dayAgo: 6,
    turns: [
      { text: "Nhân viên thì dễ thương nhưng bữa sáng dở tệ" },
      { text: "Tôi muốn đổi sang biệt thự hướng biển cho hai đêm cuối", staffReply: "Dạ em đã kiểm tra, còn Biệt Thự 2 Phòng Ngủ Hướng Biển trống. Em giữ chỗ và gửi báo giá cho anh trong 10 phút ạ." },
    ],
  },
  {
    name: "Kim Seo-yeon", phone: "+821022889046", email: "seoyeon.kim@example.kr", lang: "ko",
    vip: "none", prefs: [], notes: "친구와 여행.", stays: 1, dayAgo: 5,
    turns: [
      { text: "체크인에 한 시간이나 걸렸습니다, 정말 대단하네요" },
    ],
  },
  {
    name: "Trần Bảo Ngọc", phone: "+84945770133", email: "ngoc.tran@example.vn", lang: "vi",
    vip: "gold", prefs: ["Ăn chay"], notes: "Dị ứng hải sản.", stays: 4, dayAgo: 4,
    turns: [
      { text: "Nhà hàng có món chay không ạ?" },
      { text: "Tôi đã báo là không ăn được hải sản từ lúc đặt bàn rồi" },
    ],
  },
  {
    name: "David Okonkwo", phone: "+2348031224507", email: "d.okonkwo@example.ng", lang: "en",
    vip: "none", prefs: ["Airport transfer"], notes: "Business trip.", stays: 1, dayAgo: 3,
    turns: [
      { text: "Does the resort provide an airport shuttle, and what does it cost?" },
      { text: "Charged twice for the same dinner and nobody can explain it" },
    ],
  },
  {
    name: "Vũ Minh Anh", phone: "+84962330871", email: "anh.vu@example.vn", lang: "vi",
    vip: "silver", prefs: ["Trả phòng muộn"], notes: "Khách quay lại.", stays: 6, dayAgo: 2,
    turns: [
      { text: "Vòi sen phòng 210 bị rò nước, nhờ anh chị cho người lên xem giúp" },
    ],
  },
  {
    name: "Tanaka Kenji", phone: "+818033446721", email: "kenji.tanaka@example.jp", lang: "ja",
    vip: "gold", prefs: ["朝食"], notes: "リピーター。", stays: 8, dayAgo: 1,
    turns: [
      { text: "朝食は何時から何時までですか" },
      { text: "隣の部屋がうるさくて一睡もできませんでした" },
    ],
  },
];

/* ------------------------------------------------------------------ purge */

function purge() {
  const ids = (db.prepare(`SELECT id FROM guests WHERE notes LIKE '%${TAG}%'`).all() as any[]).map((r) => r.id);
  if (!ids.length) return console.log("khong co du lieu demo de xoa.");
  const convIds = (
    db.prepare(`SELECT id FROM conversations WHERE guest_id IN (${ids.join(",")})`).all() as any[]
  ).map((r) => r.id);
  db.transaction(() => {
    if (convIds.length) {
      for (const t of ["messages", "tasks", "trace_spans", "audit_events", "guest_requests", "service_approvals", "feedback"]) {
        db.prepare(`DELETE FROM ${t} WHERE conversation_id IN (${convIds.join(",")})`).run();
      }
      db.prepare(`DELETE FROM conversations WHERE id IN (${convIds.join(",")})`).run();
    }
    db.prepare(`DELETE FROM reservations WHERE guest_id IN (${ids.join(",")})`).run();
    db.prepare(`DELETE FROM guests WHERE id IN (${ids.join(",")})`).run();
  })();
  console.log(`da xoa ${ids.length} khach demo, ${convIds.length} hoi thoai.`);
}

/* Fixtures are the reason the dashboards were meaningless — remove them so
   every panel is computed over conversations that actually contain words. */
function purgeFixtures() {
  const ids = (
    db.prepare("SELECT id FROM conversations WHERE sentiment_source = 'seed'").all() as any[]
  ).map((r) => r.id);
  if (!ids.length) return console.log("khong con fixture seed.");
  db.transaction(() => {
    for (const t of ["messages", "tasks", "trace_spans", "audit_events", "guest_requests", "service_approvals", "feedback"]) {
      db.prepare(`DELETE FROM ${t} WHERE conversation_id IN (${ids.join(",")})`).run();
    }
    db.prepare(`DELETE FROM conversations WHERE id IN (${ids.join(",")})`).run();
    /* Seeded tasks with no conversation at all are the same fiction by another
       route: nothing raised them, and a manager clicking one cannot open the
       thread behind it because there is none. Kept once with an exception for
       `source='staff'`, which was a mistake — those 42 rows carried creation
       dates from seed time, so closing them stamped a resolution days later and
       dragged average resolution time to 5,322 minutes. Every task now traces
       to a conversation somebody actually had. */
    db.prepare("DELETE FROM tasks WHERE conversation_id IS NULL").run();
  })();
  console.log(`da xoa ${ids.length} hoi thoai fixture (sentiment_source='seed').`);
}

/* ------------------------------------------------------------------- run */

if (PURGE) {
  purge();
  process.exit(0);
}

const freeRooms = db
  .prepare(
    `SELECT id, number FROM rooms
     WHERE status != 'out_of_order'
       AND id NOT IN (SELECT room_id FROM reservations WHERE status = 'in_house' AND room_id IS NOT NULL)
     ORDER BY id`,
  )
  .all() as { id: number; number: string }[];

const fixtures = (db.prepare("SELECT COUNT(*) n FROM conversations WHERE sentiment_source='seed'").get() as any).n;
const turns = COHORT.reduce((n, p) => n + p.turns.length, 0);

console.log(`ke hoach:`);
console.log(`  xoa ${fixtures} hoi thoai fixture (rand() sentiment/topic, khong tin nhan)`);
console.log(`  tao ${COHORT.length} khach + ${COHORT.length} dat phong (${freeRooms.length} phong trong)`);
console.log(`  gui ${turns} luot khach qua API THAT -> agent that tra loi, head that cham cam xuc`);
console.log(`  ${COHORT.filter((p) => p.turns.some((t) => t.staffReply)).length} hoi thoai co nhan vien tra loi`);
console.log(`  sau do: giao + dong mot phan task qua API, roi doi timestamp trai deu 14 ngay`);
console.log(`  uoc tinh ${Math.round((turns * 10) / 60)}-${Math.round((turns * 20) / 60)} phut (moi luot la mot lan goi model that)\n`);

if (!APPLY) {
  console.log("-- DRY RUN. Chay lai voi --apply de thuc hien. --");
  process.exit(0);
}
if (freeRooms.length < COHORT.length) {
  console.error(`chi con ${freeRooms.length} phong trong, can ${COHORT.length}.`);
  process.exit(1);
}

purgeFixtures();

const today = new Date();
const iso = (d: Date) => d.toISOString();
const dayStr = (offset: number) => {
  const d = new Date(today);
  d.setDate(d.getDate() - offset);
  return d.toISOString().slice(0, 10);
};

let code = 0;
const created: { convId: number; dayAgo: number }[] = [];

for (const [i, p] of COHORT.entries()) {
  const room = freeRooms[i];
  const guest = db
    .prepare(
      `INSERT INTO guests (name, phone, email, lang, vip_tier, preferences, notes, stays_count)
       VALUES (?,?,?,?,?,?,?,?) RETURNING id`,
    )
    .get(p.name, p.phone, p.email, p.lang, p.vip, JSON.stringify(p.prefs), `${p.notes} ${TAG}`, p.stays) as any;

  const conf = `VPNT-D${String(++code).padStart(2, "0")}${Math.random().toString(36).slice(2, 6).toUpperCase()}`;
  db.prepare(
    `INSERT INTO reservations (hotel_id, guest_id, room_id, confirmation_code, check_in, check_out,
       check_out_time, adults, children, rate_per_night, status, source)
     VALUES (1,?,?,?,?,?,'12:00',?,?,?,?,?)`,
  ).run(
    guest.id, room.id, conf, dayStr(p.dayAgo + 1), dayStr(Math.max(0, p.dayAgo - 2)),
    1 + (i % 2), i % 3 === 0 ? 1 : 0, 2200000 + (i % 5) * 400000,
    p.dayAgo <= 2 ? "in_house" : "checked_out", ["direct", "booking.com", "agoda", "expedia"][i % 4],
  );

  const session = await api("/api/guest/session", { method: "POST", body: JSON.stringify({ code: conf }) });
  const convId = session.conversationId as number;
  console.log(`[${i + 1}/${COHORT.length}] ${p.name} (${p.lang}) phong ${room.number} -> hoi thoai #${convId}`);

  for (const t of p.turns) {
    const started = Date.now();
    await api(`/api/conversations/${convId}/messages`, {
      method: "POST",
      body: JSON.stringify({ body: t.text, from: "guest" }),
    });
    console.log(`      "${t.text.slice(0, 54)}..."  ${Math.round((Date.now() - started) / 1000)}s`);
    /* Give the fire-and-forget conversation analyser room to land before the
       next turn, so the topic it writes belongs to the turn that produced it. */
    await new Promise((r) => setTimeout(r, 2500));

    if (t.staffReply) {
      await api(`/api/conversations/${convId}/messages`, {
        method: "POST",
        body: JSON.stringify({ body: t.staffReply, from: "staff", staffId: 1 + (i % 6) }),
      });
      console.log(`      [nhan vien tra loi]`);
    }
  }
  created.push({ convId, dayAgo: p.dayAgo });
}

/* ------------------------------------------- staff work the board, for real */

console.log("\ndong mot phan task qua API that...");
/* Assignment is NOT done here. `storage.createTask` routes each task to the
   least-loaded active person in its department as it is created, which is the
   behaviour a demo should be showing. An earlier version of this script
   assigned with `staff.find(s => s.dept === t.dept)` — always the first match —
   and put all 46 tasks on one person, which made "Team load" look like a bug. */
const openTasks = (await api("/api/tasks")) as any[];
let assigned = openTasks.filter((t) => t.assignedStaffId != null).length;
let closed = 0;
for (const [i, t] of openTasks.entries()) {
  /* Leave roughly a third open so the board has live work — a demo where
     everything is already done shows nothing happening. */
  if (i % 3 !== 0) {
    await api(`/api/tasks/${t.id}`, { method: "PATCH", body: JSON.stringify({ status: "done" }) });
    closed++;
  }
}
console.log(`  giao ${assigned} task, dong ${closed}.`);

/* ---------------------------------------------------------- backdate only */

console.log("\ndoi timestamp de trai deu 14 ngay (noi dung khong doi)...");
const shift = db.transaction(() => {
  for (const { convId, dayAgo } of created) {
    const msgs = db
      .prepare("SELECT id, created_at FROM messages WHERE conversation_id = ? ORDER BY id")
      .all(convId) as any[];
    if (!msgs.length) continue;
    const base = new Date(today);
    base.setDate(base.getDate() - dayAgo);
    base.setHours(9 + (convId % 10), (convId * 7) % 60, 0, 0);
    const origin = new Date(msgs[0].created_at).getTime();
    const row = db.prepare("SELECT sentiment_at FROM conversations WHERE id = ?").get(convId) as any;
    for (const m of msgs) {
      /* Keep the real gaps between turns — those are measured latencies, and
         flattening them would erase the one thing the response-time cards
         actually measure. */
      const at = new Date(base.getTime() + (new Date(m.created_at).getTime() - origin));
      db.prepare("UPDATE messages SET created_at = ? WHERE id = ?").run(iso(at), m.id);
    }
    const first = iso(base);
    const last = iso(new Date(base.getTime() + (new Date(msgs[msgs.length - 1].created_at).getTime() - origin)));
    /* `sentiment_at` has to move with the messages, not be preserved. Left at
       its original wall-clock value it pointed hours after the backdated
       transcript, so "which message triggered this" resolved to the newest turn
       — the dashboard then showed an ordinary question beside a red unhappy
       badge, which reads as a false positive. */
    const shiftBy = base.getTime() - origin;
    const movedSentiment = row?.sentiment_at
      ? iso(new Date(new Date(row.sentiment_at).getTime() + shiftBy))
      : last;
    db.prepare(
      "UPDATE conversations SET created_at = ?, last_message_at = ?, sentiment_at = ? WHERE id = ?",
    ).run(first, last, movedSentiment, convId);
    db.prepare(
      `UPDATE tasks SET created_at = ?,
         resolved_at = CASE WHEN resolved_at IS NULL THEN NULL ELSE ? END,
         due_at = ?
       WHERE conversation_id = ?`,
    ).run(last, iso(new Date(new Date(last).getTime() + 42 * 60_000)), iso(new Date(new Date(last).getTime() + 10 * 60_000)), convId);
    db.prepare("UPDATE audit_events SET created_at = ? WHERE conversation_id = ?").run(last, convId);
  }
});
shift();

const stat = (sql: string) => (db.prepare(sql).get() as any).n;
console.log("\n--- ket qua ---");
console.log(`  hoi thoai           ${stat("SELECT COUNT(*) n FROM conversations")}`);
console.log(`  co tin nhan that    ${stat("SELECT COUNT(DISTINCT conversation_id) n FROM messages")}`);
console.log(`  con fixture seed    ${stat("SELECT COUNT(*) n FROM conversations WHERE sentiment_source='seed'")}`);
console.log(`  nhan tu classifier  ${stat("SELECT COUNT(*) n FROM conversations WHERE sentiment_source IN ('model_realtime','model_llm','thumbs_down')")}`);
console.log(`  task                ${stat("SELECT COUNT(*) n FROM tasks")} (${stat("SELECT COUNT(*) n FROM tasks WHERE assigned_staff_id IS NOT NULL")} da giao)`);
console.log("\nChay `npx tsx scripts/audit-insights.ts` de kiem chung.");
process.exit(0);
